<a href="https://colab.research.google.com/github/Belva99/gingervalua26/blob/main/LeccionNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Create a 1D array of numbers from 0 to 9
# your code here
import numpy as np

pass

In [8]:
# Create random vector of size 10 and replace the maximum value by 0lista=list(range(9))
print(lista)

pass

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [9]:
vector = np.random.rand(10)
vector[vector.argmax()] = 0
print(vector)

pass

[0.78008773 0.08140979 0.94466014 0.11406177 0.65254242 0.
 0.33893776 0.57737436 0.97225226 0.97948719]


In [10]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])

pass

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [11]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:])
pass

[4 5 6 7]


In [12]:

# Create a 3×3 numpy array of all True’s
tmp=10*np.random.random((4,4))
mascara=tmp>0
print(tmp)
print("-------------------")
print(mascara)
pass

[[4.39974168e+00 3.18786084e+00 4.65022586e+00 6.56036597e-01]
 [3.76110350e+00 1.78024967e+00 9.75364552e+00 1.50057387e+00]
 [7.31043504e+00 1.79620500e+00 9.19193913e-01 4.97579589e+00]
 [5.40789203e+00 2.98982839e+00 7.80379096e+00 6.51976953e-03]]
-------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [14]:
# Extract all odd numbers from arr
tmp = np.random.randint(1, 11, size=(4, 4))
print(tmp)

print('----------------------------------')

mask = np.mod(tmp, 2) == 0
print(tmp[mask])
pass


[[6 5 5 4]
 [8 8 7 6]
 [3 4 2 7]
 [1 6 4 5]]
----------------------------------
[6 4 8 8 6 4 2 6 4]


In [15]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
tmp = np.arange(10,50)
print(tmp)
pass

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
# Reverse a vector (first element becomes last)
vectorInvertido = tmp[::-1]
print(vectorInvertido)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
tmp = np.random.randint(1, 101, size=(10, 10))
minimo = np.min(tmp)
maximo = np.max(tmp)
print("Matriz")
print(tmp)
print("Minimo")
print(minimo)
print("Maximo")
print(maximo)
pass

Matriz
[[38 51 68 99 27 66 97 54 10 68]
 [ 4 37 33  7  2  4 87 47 39 52]
 [11 58 25 89 93 72 47 91 42 70]
 [44 30 61 13 99 77  9  4 94 89]
 [33 84 12 29 47 50 46 33 65 14]
 [35 55 37 62 51 43 54 18 97 60]
 [63  8 59  4 74 65 41 64 44  2]
 [83 65  9 20 55  2 65 67 72 51]
 [14 16 30 12 74 65 48 20 62 96]
 [70 43  1 72 70 70 46 42 42 56]]
Minimo
1
Maximo
99


In [18]:
# Create a 3x3x3 array with random values
tmp2 = np.random.random((3,3,3))
print(tmp2)
pass

[[[0.31545873 0.73427847 0.5453215 ]
  [0.02962133 0.38142235 0.57644786]
  [0.19990475 0.46066481 0.18268491]]

 [[0.86881759 0.57255846 0.1595506 ]
  [0.04368299 0.46272096 0.80593013]
  [0.44638531 0.58524676 0.06123025]]

 [[0.25949784 0.72479207 0.11182652]
  [0.61956031 0.65309588 0.96566945]
  [0.96652413 0.53587542 0.36733223]]]


In [19]:
# Replace all odd numbers in arr with -1
tmp = np.random.randint(1, 11, size=(3, 3, 3))
print(tmp)
print("-----------------")
tmp[tmp % 2 == 1] = -1
print(tmp)
pass

[[[ 6  6  7]
  [ 4  2  9]
  [ 9  3  1]]

 [[ 5  7  1]
  [ 5  6  5]
  [ 5  6 10]]

 [[ 9 10  9]
  [ 4  8  5]
  [ 8  2  2]]]
-----------------
[[[ 6  6 -1]
  [ 4  2 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1  6 -1]
  [-1  6 10]]

 [[-1 10 -1]
  [ 4  8 -1]
  [ 8  2  2]]]


In [20]:
# Create an array of type float
tmpF = np.random.rand(5)
print(tmpF)
pass

[0.05205437 0.18530721 0.21149254 0.90947069 0.99058249]


In [21]:
# Convert a 1D array to a 2D array with 2 rows
lista = list(range(12))
lista = np.array(lista)
two_d_array = lista.reshape(2, 6)
print(two_d_array)

pass


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [22]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
valoresComunes = np.intersect1d(Z1, Z2)
print(Z1)
print("-------------")
print(Z2)
print("-------------")
print(valoresComunes)
pass


[5 7 0 3 3 0 6 2 9 6]
-------------
[2 8 4 8 3 0 5 1 6 2]
-------------
[0 2 3 5 6]


In [23]:
#  Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print('Array A')
print(A)
print('Array B')
print(B)

if np.array_equal(A,B):
  print('Son iguales')
else:
  print('Son diferentes')

pass

Array A
[1 0 1 0 0]
Array B
[0 0 1 0 0]
Son diferentes


In [24]:
# Stack arrays a and b vertically
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaVertical = np.vstack((A, B))
print("Stacked Array:")
print(matrizApiladaVertical)
pass

Array A
[1 0 1 0 0]
Array B
[0 0 1 0 0]
Stacked Array:
[[1 0 1 0 0]
 [0 0 1 0 0]]


In [25]:
# Stack the arrays a and b horizontally.
print('Array A')
print(A)
print('Array B')
print(B)
matrizApiladaHorizontal = np.hstack((A, B))
print("Stacked Array:")
print(matrizApiladaHorizontal)
pass

Array A
[1 0 1 0 0]
Array B
[0 0 1 0 0]
Stacked Array:
[1 0 1 0 0 0 0 1 0 0]


In [26]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
print(tmp)
print('-------------')
valores = tmp[(tmp>=5)&(tmp<=10)]
print(valores)
# pass

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-------------
[ 5  6  7  8  9 10]


In [27]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


"""Arrays"""
# a = np.array([5, 7, 9, 8, 6, 4, 5])
a = np.random.randint(1,10,7)
print("Array A")
print(a)
# b = np.array([6, 3, 4, 8, 9, 7, 1])
b = np.random.randint(1,10,7)
print("Array B")
print(b)

print("----------------------------")

"""Method 1"""
print("Method 1")
def parMax(a, b):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(a, b)

c = parMax(a, b)
print(c)

print("----------------------------")

print("Method 2")
"""Method 2"""
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

c = np.array([maxx(x, y) for x, y in zip(a, b)])
print(c)

Array A
[9 4 6 8 7 3 5]
Array B
[2 2 6 8 1 8 4]
----------------------------
Method 1
[9 4 6 8 7 8 5]
----------------------------
Method 2
[9 4 6 8 7 8 5]


In [28]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("------------------------")
print("Cambio de columnas 1 y 2")
print(arr)

pass

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------
Cambio de columnas 1 y 2
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [29]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)


[[6.72380004 9.30705017 5.95051485]
 [6.24534312 5.02237586 5.01244178]
 [9.69773697 7.72668189 6.69518705]
 [6.36481405 7.31611073 5.64387657]
 [9.04136535 6.15590256 9.22722144]]
