<a href="https://colab.research.google.com/github/Belva99/gingervalua26/blob/main/nunpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[8 7 7 3]
 [2 2 9 1]
 [8 1 8 8]]
[[ 4  8  8 10]
 [ 7  9  5  2]
 [10  3  3  4]]
(3, 4)
(3, 4)
adding numbers
[[12 15 15 13]
 [ 9 11 14  3]
 [18  4 11 12]]
substracting numbers
[[ 4 -1 -1 -7]
 [-5 -7  4 -1]
 [-2 -2  5  4]]
multiply numbers
[[32 56 56 30]
 [14 18 45  2]
 [80  3 24 32]]
[[12 15 15 13]
 [ 9 11 14  3]
 [18  4 11 12]]
[[32 56 56 30]
 [14 18 45  2]
 [80  3 24 32]]
[[2.         0.875      0.875      0.3       ]
 [0.28571429 0.22222222 1.8        0.5       ]
 [0.8        0.33333333 2.66666667 2.        ]]


In [2]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[ 2  1  8]
 [ 9  2 10]]
[[ 3  9  8  2]
 [ 9  8  5  6]
 [10  3 10  3]]
[[ 95  50 101  34]
 [145 127 182  60]]
[[ 95  50 101  34]
 [145 127 182  60]]


In [3]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 7  5]
 [ 9 10]]
[[ 7  9]
 [ 5 10]]


In [4]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('------------------')
print(c)



(4, 3)
(3,)
[[8 8 3]
 [9 2 1]
 [7 5 5]
 [8 1 7]]
[1 0 2]
(4, 3)
------------------
[[8 7 7]
 [3 2 2]
 [9 1 8]
 [1 8 8]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)
print('------------------')
c=a+b
print(c)

[[8 8 3]
 [9 2 1]
 [7 5 5]
 [8 1 7]]
[1 0 2]
[[ 9  8  5]
 [10  2  3]
 [ 8  5  7]
 [ 9  1  9]]
------------------
[[ 9  8  5]
 [10  2  3]
 [ 8  5  7]
 [ 9  1  9]]


In [6]:
a=np.array([1,2,3])


#print(a)


tmp=np.tile(a,(6,1))
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)

aux=np.mean(matriz)
print(aux)
print('------------------')
matriz = np.random.randint(0, 10, size=(6, 6))
print(matriz)
print('------------------')
promedio_por_filas = np.mean(matriz, axis=1)
print("\nEl promedio por filas de la matriz es:")
print(promedio_por_filas)

[[3 6 0 9 0 1]
 [0 9 2 6 6 3]
 [5 0 8 8 8 7]
 [3 1 9 2 7 6]
 [4 7 8 9 6 4]
 [1 3 5 0 6 0]]
4.5
------------------
[[3 9 9 8 2 4]
 [8 6 2 1 3 4]
 [4 1 8 5 2 6]
 [0 9 2 2 3 0]
 [0 3 9 1 0 0]
 [8 7 4 2 1 4]]
------------------

El promedio por filas de la matriz es:
[5.83333333 4.         4.33333333 2.66666667 2.16666667 4.33333333]


In [8]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)

arr = np.array([1, 2, 3])
squared_arr = np.square(arr)

In [9]:
print(squared_arr)

[1 4 9]


In [10]:
# Broadcasting con arrays de diferentes dimensiones
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result_broadcasting = arr_2d + arr_1d

print("Resultado del Broadcasting:")
print(result_broadcasting)

# Concatenación de arrays a lo largo de diferentes ejes
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr_a, arr_b.T), axis=1)

print("\nResultado de la Concatenación:")
print(concatenated_arr)

Resultado del Broadcasting:
[[11 22 33]
 [14 25 36]]

Resultado de la Concatenación:
[[1 2 5]
 [3 4 6]]
